# This file is for GAE JAVA 25 standard

runtime: java25
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic  
  max_concurrent_requests: 30  

service: mcp-v2

inbound_services:
  - warmup

env_variables:
  HTTP_PREFIX: /api/v2/mcp

#entrypoint: ./application -Xmx352m -Xss256k -Dmcp.http.port=$PORT
entrypoint: java -Xmx352m -Xss256k -Dhttp.port=$PORT -jar mcp-service-1.0.0.jar